"use client";

import Link from "next/link";
import { useState, useEffect } from "react";
import type { Route } from "next";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Video,
  ShieldCheck,
  QrCode,
  PackageSearch,
  Activity,
  User,
  BookOpen,
  HelpCircle,
  ArrowRight,
  Signal,
  MessageSquare,
  CheckCircle,
  RefreshCw,
  Heart,
  ChevronDown,
  ChevronUp,
  Server,
  Layers,
  PhoneCall
} from "lucide-react";
import { useTranslation } from "@/components/language-provider";
import { LanguageSwitcher } from "@/components/language-switcher";

const HERO_METRICS = (isEn: boolean) => [
  { label: isEn ? "Modes" : "मोड", value: isEn ? "Video + Audio + Chat Fallback" : "वीडियो + ऑडियो + चैट बैकअप", tone: "bg-blue-light" },
  { label: isEn ? "Doctor Access" : "डॉक्टर एक्सेस", value: isEn ? "Verified Credentials Only" : "केवल सत्यापित क्रेडेंशियल्स", tone: "bg-emerald-light" },
  { label: isEn ? "Prescriptions" : "पर्चे", value: isEn ? "Secure Offline QR Engine" : "सुरक्षित ऑफलाइन क्यूआर इंजन", tone: "bg-amber-light" },
  { label: isEn ? "Connectivity" : "कनेक्टिविटी", value: isEn ? "Offline-First Sync Ready" : "ऑफ़लाइन-प्रथम सिंक सक्षम", tone: "bg-red-light" },
];

const FEATURES = (isEn: boolean) => [
  {
    icon: Video,
    title: isEn ? "Bandwidth-Adaptive Video" : "बैंडविड्थ-अनुकूल वीडियो",
    desc: isEn 
      ? "Seamless fallback from Video to Audio/Chat when signal drops, ensuring communication never cuts." 
      : "सिग्नल कम होने पर वीडियो से ऑडियो/चैट पर निर्बाध बैकअप, जिससे संचार कभी नहीं कटता।",
    tone: "bg-blue-light",
    color: "#5C94FF",
  },
  {
    icon: ShieldCheck,
    title: isEn ? "100% Verified Network" : "100% सत्यापित नेटवर्क",
    desc: isEn 
      ? "Rigorous admin approval process for doctor licenses and pharmacy registration codes." 
      : "डॉक्टर लाइसेंस और फार्मेसी पंजीकरण कोड के लिए सख्त व्यवस्थापक अनुमोदन प्रक्रिया।",
    tone: "bg-emerald-light",
    color: "#A3E635",
  },
  {
    icon: QrCode,
    title: isEn ? "Structured QR Prescriptions" : "संरचित क्यूआर पर्चे",
    desc: isEn 
      ? "Secure QR code generated by doctors with complete dosage logs, readable offline by any device." 
      : "डॉक्टरों द्वारा उत्पन्न सुरक्षित क्यूआर कोड, जिसे किसी भी डिवाइस द्वारा ऑफ़लाइन पढ़ा जा सकता है।",
    tone: "bg-amber-light",
    color: "#FCD34D",
  },
  {
    icon: PackageSearch,
    title: isEn ? "Pharmacy Transparency" : "फार्मेसी पारदर्शिता",
    desc: isEn 
      ? "Check local medicine inventories before traveling, reserve items, and update stock counts instantly." 
      : "यात्रा करने से पहले स्थानीय दवा स्टॉक की जांच करें, आइटम आरक्षित करें, और स्टॉक अपडेट करें।",
    tone: "bg-red-light",
    color: "#FF6B6B",
  },
  {
    icon: Activity,
    title: isEn ? "Smart ICU & Ambulance Routing" : "स्मार्ट आईसीयू और एम्बुलेंस रूटिंग",
    desc: isEn 
      ? "Automatic routing of ambulances to the nearest hospital with available ventilators and ICU beds." 
      : "उपलब्ध वेंटिलेटर और आईसीयू बेड वाले निकटतम अस्पताल में एम्बुलेंस का स्वचालित रूटिंग।",
    tone: "bg-blue-light",
    color: "#5C94FF",
  },
  {
    icon: Layers,
    title: isEn ? "Dynamic Traffic & Proximity Maps" : "गतिशील यातायात और निकटता मानचित्र",
    desc: isEn 
      ? "High-fidelity vector street maps with real-time traffic congestion for accurate pharmacy and emergency ETA." 
      : "सटीक फार्मेसी और आपातकालीन ईटीए के लिए वास्तविक समय यातायात भीड़ के साथ उच्च-निष्ठा वेक्टर सड़क मानचित्र।",
    tone: "bg-emerald-light",
    color: "#A3E635",
  },
  {
    icon: Heart,
    title: isEn ? "Blood Bank Tracker" : "ब्लड बैंक ट्रैकर",
    desc: isEn 
      ? "Real-time updates on blood availability across regional hubs to fulfill critical emergency requirements instantly." 
      : "महत्वपूर्ण आपातकालीन आवश्यकताओं को तुरंत पूरा करने के लिए क्षेत्रीय केंद्रों में रक्त की उपलब्धता पर वास्तविक समय अपडेट।",
    tone: "bg-amber-light",
    color: "#FCD34D",
  },
  {
    icon: QrCode,
    title: isEn ? "Interactive QR Simulator" : "इंटरएक्टिव क्यूआर सिम्युलेटर",
    desc: isEn 
      ? "Fully simulated camera viewfinder for chemists to instantly decode prescriptions and fulfill stock directly." 
      : "केमिस्टों के लिए तुरंत पर्चे डिकोड करने और स्टॉक पूरा करने के लिए पूरी तरह से सिम्युलेटेड कैमरा व्यूफाइंडर।",
    tone: "bg-blue-light",
    color: "#5C94FF",
  },
  {
    icon: RefreshCw,
    title: isEn ? "Offline Sync Center" : "ऑफलाइन सिंक केंद्र",
    desc: isEn 
      ? "Resilient IndexedDB caching to maintain operations and queue network calls seamlessly during internet outages." 
      : "इंटरनेट आउटेज के दौरान कार्यों को बनाए रखने और नेटवर्क कॉल को कतारबद्ध करने के लिए लचीला IndexedDB कैशिंग।",
    tone: "bg-emerald-light",
    color: "#A3E635",
  },
  {
    icon: User,
    title: isEn ? "AI-Powered Triage" : "एआई-संचालित ट्राइएज",
    desc: isEn 
      ? "Intelligent symptom checker to analyze your condition and recommend emergency care or routine consultations." 
      : "आपकी स्थिति का विश्लेषण करने और आपातकालीन देखभाल या नियमित परामर्श की सिफारिश करने के लिए बुद्धिमान लक्षण चेकर।",
    tone: "bg-red-light",
    color: "#FF6B6B",
  },
];

const FAQS = (isEn: boolean) => [
  {
    q: isEn ? "How does Sanjeevni work in low-connectivity areas?" : "संजीवनी कम कनेक्टिविटी वाले क्षेत्रों में कैसे काम करती है?",
    a: isEn 
      ? "Sanjeevni checks connection speed dynamically. If bandwidth drops below 100kbps, it scales the video resolution. If it drops further, it transitions to high-fidelity audio fallback with real-time text sync, storing vital data locally until full service is resumed."
      : "संजीवनी गतिशील रूप से कनेक्शन की गति की जांच करती है। यदि बैंडविड्थ 100kbps से नीचे चला जाता है, तो यह वीडियो रिज़ॉल्यूशन को कम कर देता है। यदि यह और गिरता है, तो यह रीयल-टाइम टेक्स्ट सिंक के साथ ऑडियो बैकअप पर आ जाता है।"
  },
  {
    q: isEn ? "How is doctor verification managed?" : "डॉक्टर सत्यापन कैसे प्रबंधित किया जाता है?",
    a: isEn 
      ? "Every doctor must submit their medical board license details upon registration. Platform Admins manually inspect records against databases, approving accounts before doctors can accept patients or issue prescriptions."
      : "प्रत्येक डॉक्टर को पंजीकरण पर अपने मेडिकल बोर्ड लाइसेंस विवरण जमा करने होंगे। प्लेटफॉर्म व्यवस्थापक डेटाबेस के विरुद्ध रिकॉर्ड का निरीक्षण करते हैं और अनुमोदन करते हैं।"
  },
  {
    q: isEn ? "Can pharmacies update inventory in real-time?" : "क्या फार्मेसियों वास्तविक समय में स्टॉक अपडेट कर सकती हैं?",
    a: isEn 
      ? "Yes! Pharmacies access an inventory panel where they list brand, price, and quantities. When they scan a patient's QR code, the stock levels auto-verify and decrement directly on fulfillment checkout."
      : "हाँ! फार्मेसियों एक इन्वेंटरी पैनल तक पहुँचती हैं जहाँ वे ब्रांड, मूल्य और मात्रा सूचीबद्ध करती हैं। जब वे क्यूआर कोड स्कैन करते हैं, तो स्टॉक स्वतः अपडेट हो जाता है।"
  },
  {
    q: isEn ? "Is patient medical data kept private?" : "क्या मरीज का मेडिकल डेटा निजी रखा जाता है?",
    a: isEn 
      ? "Absolutely. Patient health records are kept secure, accessible only to selected doctors during active consultations and verified pharmacists fulfilling a reservation."
      : "बिल्कुल। मरीजों के स्वास्थ्य रिकॉर्ड सुरक्षित रखे जाते हैं, जो केवल परामर्श के दौरान चुनिंदा डॉक्टरों और फार्मेसियों के लिए सुलभ होते हैं।"
  }
];

export default function Home() {
  const { t, language } = useTranslation();
  const isEn = language === "en";
  const [simStep, setSimStep] = useState(0);
  const [simRunning, setSimRunning] = useState(false);
  const [activeRoleTab, setActiveRoleTab] = useState("PATIENT");
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);
  const [mockStockLevel, setMockStockLevel] = useState(120);

  // Run mock simulator loop
  useEffect(() => {
    if (!simRunning) return;
    setSimStep(1);
    
    const timers = [
      setTimeout(() => setSimStep(2), 2200),
      setTimeout(() => setSimStep(3), 4600),
      setTimeout(() => {
        setSimStep(4);
        setMockStockLevel(prev => Math.max(0, prev - 10));
      }, 7000),
      setTimeout(() => {
        setSimRunning(false);
        setSimStep(0);
      }, 10000)
    ];

    return () => timers.forEach(t => clearTimeout(t));
  }, [simRunning]);

  return (
    <div className="min-h-screen bg-[#FFFAF0] dark:bg-[#121212] overflow-y-auto">
      {/* Header/Navbar */}
      <header className="mx-auto max-w-[1360px] px-5 pt-6 lg:px-8">
        <nav className="flex items-center justify-between border-4 border-black bg-white dark:bg-[#1E1E1E] p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.1)]">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🩺</span>
            <span className="font-black tracking-tight text-xl text-black dark:text-white">
              SANJEEVNI
            </span>
            <span className="hidden sm:inline-block pill-success text-[10px] uppercase font-black ml-2 shadow-none border-border">
              v1.0 MVP
            </span>
          </div>
          <div className="flex items-center gap-3">
            <LanguageSwitcher />
            <Link href={"/login" as Route}>
              <Button className="bg-[#A3E635] text-black border-2 border-black font-black hover:bg-lime-400 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] text-xs px-4 py-2">
                {isEn ? "Launch Portal" : "पोर्टल खोलें"}
              </Button>
            </Link>
          </div>
        </nav>
      </header>


      <div className="mx-auto w-full max-w-[1360px] space-y-12 px-5 py-8 lg:px-8 lg:py-12">
        
        {/* Hero Section */}
        <section className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
          <Card className="nb-rise bg-white dark:bg-[#1E1E1E] border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] rounded-none overflow-hidden relative">
            <div className="absolute top-0 right-0 bg-[#FF6B6B] text-black border-b-4 border-l-4 border-black font-black px-4 py-1.5 text-xs uppercase tracking-wider">
              {isEn ? "Rural Health Hub" : "ग्रामीण स्वास्थ्य केंद्र"}
            </div>
            
            <CardContent className="space-y-8 py-10 px-6 sm:px-8">
              <div className="flex flex-wrap items-center gap-2.5">
                <span className="pill-success flex items-center gap-1">
                  <Signal className="size-3" /> {isEn ? "Adaptive Bandwidth fallbacks" : "अनुकूलनीय बैंडविड्थ बैकअप"}
                </span>
                <span className="pill-info">{isEn ? "Offline-First Engine" : "ऑफ़लाइन-प्रथम इंजन"}</span>
                <span className="pill-warning">{isEn ? "Verified Doctor Hub" : "सत्यापित डॉक्टर हब"}</span>
              </div>

              <div className="space-y-4">
                <h1 className="max-w-3xl text-4xl font-black leading-[0.95] tracking-[-0.04em] text-foreground sm:text-5xl lg:text-7xl uppercase">
                  {isEn ? (
                    <>
                      Telemedicine
                      <br />
                      That Actually
                      <br />
                      <span className="bg-[#5C94FF] px-2 text-black inline-block transform -rotate-1">Works</span> Offline
                    </>
                  ) : (
                    <>
                      टेलीमेडिसिन
                      <br />
                      जो वास्तव में
                      <br />
                      <span className="bg-[#5C94FF] px-2 text-black inline-block transform -rotate-1">ऑफलाइन</span> काम करे
                    </>
                  )}
                </h1>
                <p className="max-w-2xl text-sm sm:text-base font-semibold text-muted-foreground leading-relaxed">
                  {isEn 
                    ? "Rural environments suffer from unstable networks. Sanjeevni guarantees medical advice, digital prescriptions, and local inventory checkouts even under severe packet loss."
                    : "ग्रामीण क्षेत्रों में अस्थिर नेटवर्क की समस्या होती है। संजीवनी गंभीर पैकेट हानि के बावजूद चिकित्सा सलाह, डिजिटल नुस्खे और स्थानीय दवा स्टॉक की गारंटी देती है।"}
                </p>
              </div>

              <div className="flex flex-wrap gap-4 pt-2">
                <Link href={"/login" as Route}>
                  <Button size="lg" className="bg-[#A3E635] text-black border-2 border-black font-black hover:bg-lime-400 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] text-sm px-6 py-4 nb-btn-interactive">
                    {isEn ? "Start Consultation Now" : "अभी परामर्श शुरू करें"}
                  </Button>
                </Link>
                <Link href={"/dashboard" as Route}>
                  <Button variant="outline" size="lg" className="bg-white dark:bg-[#2A2A2A] dark:text-white border-2 border-black font-black hover:bg-gray-100 dark:hover:bg-zinc-800 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] text-sm px-6 py-4 nb-btn-interactive">
                    {isEn ? "Go To Workspace" : "कार्यक्षेत्र पर जाएं"}
                  </Button>
                </Link>
              </div>

              <div className="grid gap-3 grid-cols-1 sm:grid-cols-3 pt-4 border-t-2 border-dashed border-black">
                <div className="flex items-center gap-2">
                  <span className="text-xl">📅</span>
                  <span className="text-xs font-bold text-foreground">{isEn ? "Schedule video/audio sessions" : "वीडियो/ऑडियो सत्र शेड्यूल करें"}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xl">💊</span>
                  <span className="text-xs font-bold text-foreground">{isEn ? "Structured QR prescription files" : "संरचित क्यूआर पर्चा फाइलें"}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xl">🚑</span>
                  <span className="text-xs font-bold text-foreground">{isEn ? "Interactive SOS emergency alerts" : "इंटरैक्टिव एसओएस आपातकालीन अलर्ट"}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Interactive Simulation Dashboard Mockup */}
          <div className="flex flex-col gap-4">
            <div className="border-4 border-black bg-white dark:bg-[#1E1E1E] p-6 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] relative flex-1 flex flex-col justify-between">
              <div>
                <div className="flex justify-between items-center mb-4">
                  <span className="text-xs font-black uppercase text-[#FF6B6B] tracking-wider border-2 border-black bg-red-light px-2 py-0.5 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                    {isEn ? "Simulator Window" : "सिम्युलेटर विंडो"}
                  </span>
                  <div className="flex items-center gap-1.5">
                    <span className="size-2.5 bg-red-500 rounded-full animate-ping"></span>
                    <span className="text-xs font-bold uppercase tracking-tight">{isEn ? "Active" : "सक्रिय"}</span>
                  </div>
                </div>
                <h3 className="text-lg font-black uppercase tracking-tight text-foreground mb-1">
                  {isEn ? "Rural Consultation Workflow" : "ग्रामीण परामर्श कार्यप्रवाह"}
                </h3>
                <p className="text-xs text-muted-foreground font-semibold mb-6">
                  {isEn ? "Experience how the telemedicine connection adapts in real conditions." : "अनुभव करें कि टेलीमेडिसिन कनेक्शन वास्तविक परिस्थितियों में कैसे अनुकूलित होता है।"}
                </p>
              </div>

              {/* Viewport content */}
              <div className="border-4 border-black bg-black rounded-none min-h-[200px] flex flex-col items-center justify-center p-4 relative overflow-hidden">
                <div className="absolute inset-0 bg-[radial-gradient(#2A2A2A_1px,transparent_1px)] [background-size:16px_16px] opacity-40"></div>
                
                {simStep === 0 && (
                  <div className="text-center z-10 space-y-4">
                    <span className="text-5xl block animate-bounce">📡</span>
                    <div className="space-y-1">
                      <div className="text-[#A3E635] text-xs font-black uppercase tracking-wider">
                        {isEn ? "Telemetry Systems Ready" : "टेलीमेट्री सिस्टम तैयार"}
                      </div>
                      <p className="text-[10px] text-gray-400 max-w-[220px]">
                        {isEn ? "Start the mock sequence to watch fallback routing in action." : "बैकअप रूटिंग देखने के लिए मॉक अनुक्रम शुरू करें।"}
                      </p>
                    </div>
                    <Button 
                      onClick={() => setSimRunning(true)}
                      className="bg-[#A3E635] text-black border-2 border-black font-black hover:bg-lime-400 text-xs shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] px-4 py-1.5"
                    >
                      {isEn ? "▶ Run Simulation Flow" : "▶ सिमुलेशन शुरू करें"}
                    </Button>
                  </div>
                )}

                {simStep === 1 && (
                  <div className="text-center z-10 space-y-3 p-4">
                    <div className="flex justify-center gap-1">
                      <Signal className="text-[#FF6B6B] size-8 animate-pulse" />
                    </div>
                    <div className="text-[#FF6B6B] text-xs font-black uppercase">
                      {isEn ? "Poor Connection Alert" : "कमजोर कनेक्शन चेतावनी"}
                    </div>
                    <div className="bg-[#1E1E1E] border border-red-500 p-2 text-left font-mono text-[9px] text-[#FF6B6B] rounded space-y-1 max-w-[240px]">
                      <div>&gt; latency check: 450ms</div>
                      <div>&gt; packet loss: 12% (Poor 2G)</div>
                      <div className="text-white font-bold">&gt; Action: {isEn ? "fall back to Audio + Text Sync" : "ऑडियो + टेक्स्ट सिंक पर बैकअप"}</div>
                    </div>
                  </div>
                )}

                {simStep === 2 && (
                  <div className="w-full z-10 space-y-3">
                    <div className="flex items-center gap-2 justify-between border-b border-gray-800 pb-2">
                      <div className="flex items-center gap-1">
                        <PhoneCall className="text-[#A3E635] size-4 animate-bounce" />
                        <span className="text-[10px] text-white font-bold uppercase">{isEn ? "Live Audio Call" : "लाइव ऑडियो कॉल"}</span>
                      </div>
                      <span className="text-[9px] text-gray-400 font-bold bg-gray-900 px-1 border border-gray-800 rounded">
                        00:14
                      </span>
                    </div>

                    <div className="space-y-2">
                      <div className="bg-[#1E1E1E] p-2 text-left border-l-2 border-[#5C94FF] rounded text-[10px]">
                        <span className="text-[#5C94FF] font-black block text-[8px] uppercase">Dr. Sanjeev</span>
                        <p className="text-white font-medium">"Sumit, your throat inflammation is minor. I am prescribing Paracetamol and Lozenges."</p>
                      </div>
                      <div className="bg-[#1E1E1E] p-2 text-left border-l-2 border-[#A3E635] rounded text-[10px]">
                        <span className="text-[#A3E635] font-black block text-[8px] uppercase">Patient (Sumit)</span>
                        <p className="text-white font-medium">"Thank you, doctor. I will check the stock at our village pharmacy."</p>
                      </div>
                    </div>
                  </div>
                )}

                {simStep === 3 && (
                  <div className="text-center z-10 space-y-2">
                    <div className="mx-auto w-16 h-16 bg-white border border-[#FCD34D] p-1 rounded">
                      <div className="w-full h-full border-2 border-black flex items-center justify-center font-bold text-xs text-black">
                        QR
                      </div>
                    </div>
                    <div className="text-[#FCD34D] text-xs font-black uppercase tracking-wider">
                      {isEn ? "QR Prescription Generated" : "क्यूआर पर्चा जनरेट हुआ"}
                    </div>
                    <div className="text-[9px] text-gray-400 font-mono">
                      RxToken: SANJEEVNI_RX:YUKTI_MOCK
                    </div>
                    <div className="bg-[#1E1E1E] border border-dashed border-gray-800 p-1.5 rounded max-w-[200px] text-[9px] text-left text-white mx-auto font-bold">
                      💊 Paracetamol 500mg (Qty: 10)
                    </div>
                  </div>
                )}

                {simStep === 4 && (
                  <div className="text-center z-10 space-y-3">
                    <CheckCircle className="text-[#A3E635] size-8 mx-auto animate-bounce" />
                    <div className="text-[#A3E635] text-xs font-black uppercase">
                      {isEn ? "Stock Fulfilled & Checked Out" : "स्टॉक पूर्ण और चेक आउट"}
                    </div>
                    <div className="bg-[#1E1E1E] p-2 rounded text-[10px] border border-gray-800 text-left font-mono max-w-[240px] space-y-1">
                      <div className="text-gray-400">{isEn ? "Village Pharmacy:" : "ग्राम फार्मेसी:"}</div>
                      <div className="text-[#A3E635] font-bold">
                        {isEn ? "Stock:" : "स्टॉक:"} 100 units ➔ {mockStockLevel} units
                      </div>
                      <div className="text-white font-bold">&gt; {isEn ? "Reservation code:" : "आरक्षण कोड:"} LOCKED-92</div>
                    </div>
                  </div>
                )}

              </div>

              {/* Status indicators */}
              <div className="mt-4 pt-4 border-t border-gray-200 dark:border-zinc-800 flex items-center justify-between">
                <div className="flex gap-2">
                  <span className={`w-2.5 h-2.5 rounded-full ${simStep >= 1 ? "bg-[#FF6B6B]" : "bg-gray-300 dark:bg-zinc-700"}`}></span>
                  <span className={`w-2.5 h-2.5 rounded-full ${simStep >= 2 ? "bg-[#5C94FF]" : "bg-gray-300 dark:bg-zinc-700"}`}></span>
                  <span className={`w-2.5 h-2.5 rounded-full ${simStep >= 3 ? "bg-[#FCD34D]" : "bg-gray-300 dark:bg-zinc-700"}`}></span>
                  <span className={`w-2.5 h-2.5 rounded-full ${simStep >= 4 ? "bg-[#A3E635]" : "bg-gray-300 dark:bg-zinc-700"}`}></span>
                </div>
                <span className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">
                  {simRunning 
                    ? (isEn ? "Simulating Consult Flow..." : "सिमुलेशन चल रहा है...") 
                    : (isEn ? "Ready to Simulate" : "सिमुलेशन के लिए तैयार")}
                </span>
              </div>
            </div>
          </div>
        </section>

        {/* Metrics Grid */}
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {HERO_METRICS(isEn).map((metric, index) => (
            <Card key={metric.label} className={`nb-card-interactive shadow-soft bg-white dark:bg-[#1E1E1E] border-2 border-black`}>
              <CardContent className="py-5 px-6">
                <div className="text-xs font-black uppercase tracking-[0.08em] text-muted-foreground">
                  {metric.label}
                </div>
                <div className="mt-1 text-base font-black tracking-tight text-foreground">
                  {metric.value}
                </div>
              </CardContent>
            </Card>
          ))}
        </section>

        {/* Core Features */}
        <section className="space-y-6">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="pill-info uppercase text-xs font-black">{isEn ? "Feature Suite" : "सुविधा सूची"}</span>
            <h2 className="text-3xl font-black uppercase tracking-tight text-foreground sm:text-4xl">
              {isEn ? "Engineered For Remote Reality" : "रिमोट रियलिटी के लिए निर्मित"}
            </h2>
            <p className="text-sm font-semibold text-muted-foreground">
              {isEn ? "Built on clean data models, offline queues, and instant sync triggers." : "स्वच्छ डेटा मॉडल, ऑफ़लाइन कतारों और त्वरित सिंक ट्रिगर पर निर्मित।"}
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURES(isEn).map((feature, index) => {
              const Icon = feature.icon;
              return (
                <Card key={feature.title} className={`${feature.tone} nb-card-interactive border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-none`}>
                  <CardContent className="space-y-4 py-6 px-5 flex flex-col justify-between h-full">
                    <div className="space-y-4">
                      <div className="inline-flex rounded-lg border-2 border-black bg-white p-2.5 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                        <Icon className="size-6 text-black" />
                      </div>
                      <h3 className="text-xl font-black uppercase leading-none tracking-tight">{feature.title}</h3>
                      <p className="text-xs font-bold text-muted-foreground leading-relaxed">{feature.desc}</p>
                    </div>
                    <div className="pt-2 text-[10px] font-black uppercase tracking-wide text-foreground/60">
                      {isEn ? `Core Outpost Feature ${index + 1}` : `मुख्य आउटपोस्ट विशेषता ${index + 1}`}
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </section>

        {/* Roles Tab System Section */}
        <section className="border-4 border-black bg-white dark:bg-[#1E1E1E] p-6 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
          <div className="flex flex-wrap items-center justify-between gap-4 border-b-2 border-black pb-4 mb-6">
            <div>
              <h2 className="text-2xl font-black uppercase tracking-tight text-foreground">
                {isEn ? "Role-Based Portal Breakdown" : "भूमिका-आधारित पोर्टल विवरण"}
              </h2>
              <p className="text-xs text-muted-foreground font-semibold">
                {isEn ? "Explore individual portal features tailored to patients, doctors, chemists, and admins." : "मरीजों, डॉक्टरों, केमिस्टों और व्यवस्थापकों के लिए तैयार की गई व्यक्तिगत पोर्टल सुविधाओं का पता लगाएं।"}
              </p>
            </div>
            
            {/* Tab buttons */}
            <div className="flex flex-wrap gap-2">
              {["PATIENT", "DOCTOR", "PHARMACY", "ADMIN"].map((role) => (
                <button
                  key={role}
                  onClick={() => setActiveRoleTab(role)}
                  className={`border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-wider transition-all duration-100 ${
                    activeRoleTab === role
                      ? "bg-[#5C94FF] text-black translate-x-[-1px] translate-y-[-1px] shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
                      : "bg-white dark:bg-[#2A2A2A] text-foreground hover:bg-gray-100 dark:hover:bg-zinc-800"
                  }`}
                >
                  {role === "PATIENT" ? (isEn ? "Patient" : "मरीज़") :
                   role === "DOCTOR" ? (isEn ? "Doctor" : "चिकित्सक") :
                   role === "PHARMACY" ? (isEn ? "Pharmacy" : "फार्मेसी") :
                   (isEn ? "Admin" : "व्यवस्थापक")}
                </button>
              ))}
            </div>
          </div>

          {/* Tab Content Display */}
          <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
            <div className="space-y-4">
              {activeRoleTab === "PATIENT" && (
                <div className="space-y-4">
                  <div className="pill-success text-xs font-black inline-block">{isEn ? "Patient Workspace" : "मरीज़ कार्यक्षेत्र"}</div>
                  <h3 className="text-xl font-black uppercase tracking-tight text-foreground">{isEn ? "Distress Relief & Simple Booking" : "संकट राहत और सरल बुकिंग"}</h3>
                  <p className="text-xs text-muted-foreground font-semibold leading-relaxed">
                    {isEn 
                      ? "Designed with high readability and contrast. Patients can check symptoms, review doctor consultations, receive digital prescriptions via local QR files, and upload health history metrics securely."
                      : "उच्च पठनीयता और कंट्रास्ट के साथ डिज़ाइन किया गया। मरीज लक्षणों की जांच कर सकते हैं, डॉक्टरों से परामर्श ले सकते हैं, स्थानीय क्यूआर फाइलों के माध्यम से डिजिटल नुस्खे प्राप्त कर सकते हैं।"}
                  </p>
                  
                  <div className="space-y-2 pt-2">
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-emerald font-bold">✓</span> {isEn ? "Symptom Triage with urgency scale blocks" : "अति आवश्यक पैमाने के ब्लॉक के साथ लक्षण जांच"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-emerald font-bold">✓</span> {isEn ? "One-button Emergency SOS distress broadcast" : "एक बटन आपातकालीन एसओएस संकट प्रसारण"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-emerald font-bold">✓</span> {isEn ? "Offline reservation and stock checks at village chemists" : "गांव के केमिस्टों के पास ऑफ़लाइन आरक्षण और स्टॉक जांच"}
                    </div>
                  </div>
                </div>
              )}

              {activeRoleTab === "DOCTOR" && (
                <div className="space-y-4">
                  <div className="pill-info text-xs font-black inline-block">{isEn ? "Doctor Workspace" : "चिकित्सक कार्यक्षेत्र"}</div>
                  <h3 className="text-xl font-black uppercase tracking-tight text-foreground">{isEn ? "Consultation & Digital Prescriptions" : "परामर्श और डिजिटल नुस्खे"}</h3>
                  <p className="text-xs text-muted-foreground font-semibold leading-relaxed">
                    {isEn 
                      ? "Doctors manage their schedules, accept incoming consult rooms, and write structured medicine plans. Prescriptions enforce specific dosage durations to prevent drug abuse and incorrect usage."
                      : "चिकित्सक अपने कार्यक्रम का प्रबंधन करते हैं, आने वाले परामर्श कक्षों को स्वीकार करते हैं, और दवा योजनाएं लिखते हैं।"}
                  </p>
                  
                  <div className="space-y-2 pt-2">
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-primary font-bold">✓</span> {isEn ? "Secure login credentials backed by custom hashing" : "कस्टम हैशिंग द्वारा समर्थित सुरक्षित लॉगिन क्रेडेंशियल"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-primary font-bold">✓</span> {isEn ? "Live consultation viewport control (Go Live/Closed)" : "लाइव परामर्श व्यूपोर्ट नियंत्रण (गो लाइव/बंद)"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-primary font-bold">✓</span> {isEn ? "Structured dosage generators that sync QR files instantly" : "संरचित खुराक जनरेटर जो क्यूआर फाइलों को तुरंत सिंक करते हैं"}
                    </div>
                  </div>
                </div>
              )}

              {activeRoleTab === "PHARMACY" && (
                <div className="space-y-4">
                  <div className="pill-warning text-xs font-black inline-block">{isEn ? "Pharmacy Station" : "फार्मेसी स्टेशन"}</div>
                  <h3 className="text-xl font-black uppercase tracking-tight text-foreground">{isEn ? "Stock Fulfillments & QR Checkouts" : "स्टॉक पूर्णता और क्यूआर चेकआउट"}</h3>
                  <p className="text-xs text-muted-foreground font-semibold leading-relaxed">
                    {isEn 
                      ? "Local pharmacies check incoming reservations, handle inventory levels, scan QR codes using viewfinders, and fulfill prescriptions while auto-deducting stocks to keep the community database accurate."
                      : "स्थानीय फार्मेसियों आने वाले आरक्षणों की जांच करती हैं, इन्वेंट्री स्तरों को संभालती हैं, और क्यूआर कोड स्कैन करके नुस्खे पूरा करती हैं।"}
                  </p>
                  
                  <div className="space-y-2 pt-2">
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-[#FCD34D] font-bold">✓</span> {isEn ? "Simulated camera viewfinder with CSS laser scanning" : "सीएसएस लेजर स्कैनिंग के साथ सिम्युलेटेड कैमरा व्यूफाइंडर"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-[#FCD34D] font-bold">✓</span> {isEn ? "Automatic stock matching on prescription loading" : "पर्चा लोड होने पर स्वचालित स्टॉक मिलान"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-[#FCD34D] font-bold">✓</span> {isEn ? "Instant inventory updates via PATCH endpoint integrations" : "पैच एंडपॉइंट एकीकरण के माध्यम से तत्काल इन्वेंट्री अपडेट"}
                    </div>
                  </div>
                </div>
              )}

              {activeRoleTab === "ADMIN" && (
                <div className="space-y-4">
                  <div className="pill-danger text-xs font-black inline-block">{isEn ? "Admin Console" : "व्यवस्थापक कंसोल"}</div>
                  <h3 className="text-xl font-black uppercase tracking-tight text-foreground">{isEn ? "Operation Monitoring & SOS Dispatches" : "संचालन निगरानी और एसओएस प्रेषण"}</h3>
                  <p className="text-xs text-muted-foreground font-semibold leading-relaxed">
                    {isEn 
                      ? "Admins approve practitioner credentials, monitor logs, and dispatch community assistance. Features include a GPS outpost map showing real-time distress signals."
                      : "व्यवस्थापक चिकित्सकों के क्रेडेंशियल को मंजूरी देते हैं, लॉग की निगरानी करते हैं, और एसओएस आपातकालीन प्रतिक्रिया का प्रबंधन करते हैं।"}
                  </p>
                  
                  <div className="space-y-2 pt-2">
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-red font-bold">✓</span> {isEn ? "Interactive SVG GPS community outpost map" : "इंटरैक्टिव एसवीजी जीपीएस समुदाय आउटपोस्ट मानचित्र"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-red font-bold">✓</span> {isEn ? "Live ambulance dispatch coordinates tracking" : "लाइव एम्बुलेंस प्रेषण निर्देशांक ट्रैकिंग"}
                    </div>
                    <div className="border-2 border-black bg-[#FFFAF0] dark:bg-[#121212] p-3 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] text-xs font-black flex items-center gap-2">
                      <span className="text-red font-bold">✓</span> {isEn ? "Practitioner credential verification queues" : "चिकित्सक क्रेडेंशियल सत्यापन कतार"}
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Mock Dashboard preview frame */}
            <div className="border-4 border-black bg-[#FFFAF0] dark:bg-[#121212] p-5 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex flex-col justify-between min-h-[260px] relative">
              <div className="absolute top-2 right-2 flex gap-1">
                <span className="size-2 rounded-full bg-red-500"></span>
                <span className="size-2 rounded-full bg-yellow-500"></span>
                <span className="size-2 rounded-full bg-green-500"></span>
              </div>
              
              {activeRoleTab === "PATIENT" && (
                <div className="space-y-4">
                  <div className="border-b border-black pb-2 flex justify-between items-center">
                    <span className="text-xs font-black text-black dark:text-white uppercase">{isEn ? "Patient Workspace" : "मरीज़ कार्यक्षेत्र"}</span>
                    <span className="text-[10px] text-gray-500 font-bold">Sumit</span>
                  </div>
                  <div className="border-2 border-black bg-[#A3E635] p-3 text-xs text-black font-black flex justify-between items-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                    <div>
                      <span className="block text-[10px] uppercase text-black/70">{isEn ? "Consultation Scheduled" : "परामर्श अनुसूचित"}</span>
                      <span>Dr. Sanjeev (General Physician)</span>
                    </div>
                    <span className="pill-success bg-white text-xs border border-black shadow-none">{isEn ? "Live Room" : "लाइव रूम"}</span>
                  </div>
                  <div className="border-2 border-black bg-white dark:bg-[#2A2A2A] p-2.5 text-xs text-foreground font-bold shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                    🩺 {isEn ? "Current Triage Status:" : "वर्तमान स्थिति:" } <span className="pill-warning bg-amber-light text-[10px] ml-1">{isEn ? "Urgent / Yellow" : "अति आवश्यक / पीला"}</span>
                  </div>
                </div>
              )}

              {activeRoleTab === "DOCTOR" && (
                <div className="space-y-4">
                  <div className="border-b border-black pb-2 flex justify-between items-center">
                    <span className="text-xs font-black text-black dark:text-white uppercase">{isEn ? "Doctor Console" : "डॉक्टर कंसोल"}</span>
                    <span className="text-[10px] text-gray-500 font-bold">Dr. Sanjeev</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div className="border-2 border-black bg-white dark:bg-[#2A2A2A] p-2 text-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                      <span className="block text-xs font-black text-muted-foreground">{isEn ? "Today's Slots" : "आज के स्लॉट"}</span>
                      <span className="text-lg font-black text-foreground">{isEn ? "6 Slots" : "6 स्लॉट"}</span>
                    </div>
                    <div className="border-2 border-black bg-white dark:bg-[#2A2A2A] p-2 text-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                      <span className="block text-xs font-black text-muted-foreground">{isEn ? "Queue" : "कतार"}</span>
                      <span className="text-lg font-black text-foreground">{isEn ? "2 Waiting" : "2 प्रतीक्षारत"}</span>
                    </div>
                  </div>
                  <Button size="xs" className="w-full bg-[#5C94FF] text-black border-2 border-black font-black uppercase text-[10px] py-1.5 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                    {isEn ? "Generate Secure QR Prescription" : "सुरक्षित क्यूआर पर्चा जनरेट करें"}
                  </Button>
                </div>
              )}

              {activeRoleTab === "PHARMACY" && (
                <div className="space-y-4">
                  <div className="border-b border-black pb-2 flex justify-between items-center">
                    <span className="text-xs font-black text-black dark:text-white uppercase">{isEn ? "Pharmacy stock" : "फार्मेसी स्टॉक"}</span>
                    <span className="text-[10px] text-gray-500 font-bold">{isEn ? "Rural Outpost Chemist" : "ग्रामीण आउटपोस्ट केमिस्ट"}</span>
                  </div>
                  <div className="space-y-1.5">
                    <div className="flex justify-between items-center text-xs font-bold border-b border-dashed border-black pb-1">
                      <span>Paracetamol 500mg</span>
                      <span className="pill-success text-[10px]">{isEn ? "90 units" : "90 यूनिट"}</span>
                    </div>
                    <div className="flex justify-between items-center text-xs font-bold border-b border-dashed border-black pb-1">
                      <span>Amoxicillin 250mg</span>
                      <span className="pill-success text-[10px]">{isEn ? "45 units" : "45 यूनिट"}</span>
                    </div>
                    <div className="flex justify-between items-center text-xs font-bold border-b border-dashed border-black pb-1">
                      <span>Cough Syrup Lozenges</span>
                      <span className="pill-danger text-[10px]">{isEn ? "Out of stock" : "स्टॉक में नहीं"}</span>
                    </div>
                  </div>
                </div>
              )}

              {activeRoleTab === "ADMIN" && (
                <div className="space-y-4">
                  <div className="border-b border-black pb-2 flex justify-between items-center">
                    <span className="text-xs font-black text-black dark:text-white uppercase">{isEn ? "Outpost map" : "आउटपोस्ट मैप"}</span>
                    <span className="text-[10px] text-gray-500 font-bold">{isEn ? "HQ Panel" : "मुख्यालय पैनल"}</span>
                  </div>
                  <div className="border-2 border-black bg-red-light p-2.5 rounded text-xs text-black font-black flex items-center justify-between shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                    <div className="flex items-center gap-1.5">
                      <span className="size-2 bg-red-500 rounded-full animate-ping"></span>
                      <span>{isEn ? "Active distress (Coordinates: GP-90, LA-12)" : "सक्रिय संकट (निर्देशांक: GP-90, LA-12)"}</span>
                    </div>
                    <span className="pill-danger text-[9px] bg-white border border-black shadow-none">{isEn ? "Broadcasting" : "प्रसारण चालू"}</span>
                  </div>
                </div>
              )}

              <div className="mt-4 text-[9px] font-black uppercase text-center tracking-wider text-muted-foreground">
                {isEn ? "Interactive Mockup Screen" : "इंटरैक्टिव मॉकअप स्क्रीन"}
              </div>
            </div>
          </div>
        </section>

        {/* FAQs */}
        <section className="space-y-6">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="pill-warning uppercase text-xs font-black">{isEn ? "Get Answers" : "उत्तर प्राप्त करें"}</span>
            <h2 className="text-3xl font-black uppercase tracking-tight text-foreground sm:text-4xl">
              {isEn ? "Frequently Asked Questions" : "अक्सर पूछे जाने वाले प्रश्न"}
            </h2>
            <p className="text-sm font-semibold text-muted-foreground">
              {isEn ? "Everything you need to know about the platform's features and safety protocols." : "प्लेटफ़ॉर्म की विशेषताओं और सुरक्षा प्रोटोकॉल के बारे में जानने योग्य बातें।"}
            </p>
          </div>

          <div className="max-w-3xl mx-auto space-y-3">
            {FAQS(isEn).map((faq, index) => (
              <div
                key={index}
                className="border-2 border-black bg-white dark:bg-[#1E1E1E] shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all duration-150"
              >
                <button
                  onClick={() => setExpandedFaq(expandedFaq === index ? null : index)}
                  className="w-full flex justify-between items-center p-4 text-left font-black uppercase tracking-tight text-sm text-foreground focus:outline-none"
                >
                  <span>{faq.q}</span>
                  {expandedFaq === index ? <ChevronUp className="size-4 text-black dark:text-white" /> : <ChevronDown className="size-4 text-black dark:text-white" />}
                </button>
                {expandedFaq === index && (
                  <div className="p-4 pt-0 text-xs font-bold text-muted-foreground border-t-2 border-dashed border-black leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Call To Action banner */}
        <section className="nb-pop">
          <div className="rounded-none border-4 border-black bg-black p-8 text-white shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] dark:shadow-[8px_8px_0px_0px_rgba(255,255,255,0.1)] lg:p-12">
            <div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-black uppercase tracking-tight text-white sm:text-4xl">
                  {isEn ? "Ready to launch rural health access?" : "ग्रामीण स्वास्थ्य पहुंच शुरू करने के लिए तैयार हैं?"}
                </h2>
                <p className="max-w-2xl text-xs sm:text-sm font-semibold text-gray-400 leading-relaxed">
                  {isEn 
                    ? "Join the network of doctors, patients, and local pharmacies. Sign up and explore the telemedicine panel, local DB synchronization, and instant prescription fulfillments."
                    : "डॉक्टरों, मरीजों और स्थानीय फार्मेसियों के नेटवर्क से जुड़ें। साइन अप करें और टेलीमेडिसिन पैनल, स्थानीय डेटाबेस सिंक और तत्काल पर्चे पूरे होने की प्रक्रिया का पता लगाएं।"}
                </p>
              </div>
              <div className="flex flex-wrap gap-4">
                <Link href={"/login" as Route}>
                  <Button size="lg" className="bg-[#A3E635] text-black border-2 border-black font-black hover:bg-lime-400 shadow-[4px_4px_0px_0px_rgba(255,255,255,0.2)] text-sm px-6 py-4 nb-btn-interactive">
                    {isEn ? "Launch App Portal" : "ऐप पोर्टल लॉन्च करें"}
                  </Button>
                </Link>
                <Link href={"/dashboard" as Route}>
                  <Button size="lg" variant="outline" className="bg-transparent border-2 border-white text-white font-black hover:bg-zinc-900 shadow-[4px_4px_0px_0px_rgba(255,255,255,0.2)] text-sm px-6 py-4 nb-btn-interactive">
                    {isEn ? "View Workspace" : "कार्यक्षेत्र देखें"}
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Footer */}
      <footer className="border-t-4 border-black bg-white dark:bg-[#1E1E1E] py-8 mt-12 shadow-[0_-4px_0px_0px_rgba(0,0,0,1)]">
        <div className="mx-auto max-w-[1360px] px-5 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-black uppercase tracking-wider text-muted-foreground">
          <div className="flex items-center gap-2 text-foreground">
            <span>🩺</span>
            <span>{isEn ? "Sanjeevni Rural Telemedicine System" : "संजीवनी ग्रामीण टेलीमेडिसिन प्रणाली"}</span>
          </div>
          <div>
            &copy; 2026 Sanjeevni · {isEn ? "All Rights Reserved" : "सर्वाधिकार सुरक्षित"}
          </div>
        </div>
      </footer>
    </div>
  );
}
